functionsDirectory = "C:\\Users\\animeshmanna\\Desktop\\sarad_sangha_club\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\animeshmanna\\Desktop\\sarad_sangha_club"
publishOrigin = "config"
functions = "C:\\Users\\animeshmanna\\Desktop\\sarad_sangha_club\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]